aws_region="us-east-1"
environment="uat"
vpc_tag_name="*nonprod"
db_name= "sudhakar-uat"
db_allocated_storage = 100
app_environment = "dev"
db_instance_class = "db.m5.large"
db_username = "sudhakar"
db_multi_az = false
