variable "vpc_cidr" {}
variable "vpc_name" {}
variable "IGW_name" {}
variable "environment" {}
variable "public_subnet1_cidr" {}
variable "public_subnet2_cidr" {}
variable "private_subnet1_cidr" {}
variable "private_subnet2_cidr" {}
variable "public_subnet1_name" {}
variable "public_subnet2_name" {}
variable "private_subnet1_name" {}
variable "private_subnet2_name" {}
variable "public_routing_table" {}
variable "private_routing_table" {}